appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} {l:<5} {t} - {m}{n}"

root:
  level: debug
  appenders:
    - stdout